server:
  port: 8091
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://47.99.243.19:3306/leyou?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    jackson:
      default-property-inclusion: non_null
    redis:
      host: 192.168.1.58
    rabbitmq:
      host: 192.168.1.76
      username: admin
      password: admin
      virtual-host: /imall
      template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 30000ms
          multiplier: 2
        exchange: im.item.exchange
      publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
  mybatis:
    type-aliases-package: com.imall.order.pojo
  im:
    jwt:
      pubKeyPath: /home/zyl/rsa/id_rsa.pub # 公钥地址
      cookieName: LY_TOKEN # cookie的名称
    worker:
      workerId: 1
      dataCenterId: 1
    pay:
      appId: wx8397f8696b538317
      mchId: 1473426802
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
      connectTimeoutMs: 5000
      readTimeoutMs: 10000
      notifyUrl: http://h7rmfa.natappfree.cc/wxpay/notify



