server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /imall
    username: admin
    password: admin
    host: 192.168.1.76
  redis:
    host: 192.168.1.58
im:
  sms:
    accessKeyId: LTAI4FjhWv1qzkhEt1i2GuTt
    accessKeySecret: pYD1RWGnryqJeOi3SDDIeBEmaucX0h
    signName: 叮咚商城 # 签名名称
    verifyCodeTemplate: SMS_174022562
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}